apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-remx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-remx
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-remx
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-remx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-remx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-obwl-tenant/rhtap-demo-app/hacbs-test-project-remx@sha256:f3fdcbda1fcd9d48555bbc89b32c27d1c4101d97bbf1f6a8377b35394153cec0
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
