apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-remx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-obwl-tenant/rhtap-demo-app/hacbs-test-project-remx@sha256:a99e7019e26834d4579e03a356b4f2da6064992dd4631f7c6b4e469bc2d0b23d
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
